Repository elastic/apm-agent-go, pull requests merged in 2018-11, with the labels that each got.

#299 Introduce Transaction.EnsureParent
  docs/api.asciidoc
  example_tracecontext_test.go
  transaction.go
  transaction_test.go
Labels: [zube]: In Review

#313 Introduce default internal logger
  CHANGELOG.md
  docs/configuration.asciidoc
  internal/apmdebug/debug.go
  internal/apmlog/logger.go
  tracer.go
  vendor/github.com/rs/zerolog/LICENSE
  vendor/github.com/rs/zerolog/array.go
  vendor/github.com/rs/zerolog/console.go
  vendor/github.com/rs/zerolog/context.go
  vendor/github.com/rs/zerolog/ctx.go
  vendor/github.com/rs/zerolog/encoder.go
  vendor/github.com/rs/zerolog/encoder_json.go
  vendor/github.com/rs/zerolog/event.go
  vendor/github.com/rs/zerolog/fields.go
  vendor/github.com/rs/zerolog/globals.go
  vendor/github.com/rs/zerolog/go.mod
  vendor/github.com/rs/zerolog/hook.go
  vendor/github.com/rs/zerolog/internal/json/base.go
  vendor/github.com/rs/zerolog/internal/json/bytes.go
  vendor/github.com/rs/zerolog/internal/json/string.go
  vendor/github.com/rs/zerolog/internal/json/time.go
  vendor/github.com/rs/zerolog/internal/json/types.go
  vendor/github.com/rs/zerolog/log.go
  vendor/github.com/rs/zerolog/sampler.go
  vendor/github.com/rs/zerolog/syslog.go
  vendor/github.com/rs/zerolog/writer.go
  vendor/vendor.json
Labels: [zube]: In Review

#325 transport: implement ELASTIC_APM_SERVER_CERT
  docs/configuration.asciidoc
  transport/http.go
  transport/http_test.go
  transport/testdata/cert.pem
  transport/testdata/key.pem
Labels: [zube]: In Review

#331 docs: update introduction
  docs/index.asciidoc
  docs/introduction.asciidoc
Labels: docs

#292 [Jenkins] Go Agent Pipeline version 0
  Jenkinsfile
  README.md
  scripts/jenkins/bench.sh
  scripts/jenkins/build.sh
  scripts/jenkins/common.bash
  scripts/jenkins/docker-test.sh
  scripts/jenkins/test.sh
Labels: [zube]: In Review

#332 Introduce Span.Subtype, Span.Action
  CHANGELOG.md
  docs/api.asciidoc
  model/marshal_fastjson.go
  model/model.go
  modelwriter.go
  module/apmgocql/apmgocql_test.go
  module/apmgrpc/client_test.go
  module/apmhttp/client.go
  module/apmhttp/client_test.go
  module/apmot/example_test.go
  module/apmot/span.go
  module/apmot/tracer_test.go
  module/apmredigo/conn.go
  module/apmredigo/conn_test.go
  module/apmsql/apmsql_go110_test.go
  module/apmsql/apmsql_test.go
  module/apmsql/mysql/mysql_test.go
  module/apmsql/pq/pq_test.go
  span.go
  span_test.go
Labels: [zube]: In Review

#326 StartSpanOptions ignored options parameter
  apmtest/withtransaction.go
  gocontext.go
  gocontext_test.go
  span.go
Labels: [zube]: In Review, bug
