Repository elastic/apm-agent-go, pull requests merged in 2019-07, with the labels that each got.

#575 Fix body capture to ignore read errors
  capturebody.go
  internal/apmhttputil/url.go
  internal/apmstrings/truncate.go
  internal/apmstrings/truncate_test.go
  module/apmhttp/handler_test.go
  utils.go
Labels: [zube]: In Progress

#564 Breakdown metrics
  CHANGELOG.md
  apmtest/recordlogger.go
  breakdown.go
  breakdown_test.go
  builtin_metrics.go
  docs/metrics.asciidoc
  env.go
  fnv.go
  fnv_test.go
  internal/apmlog/logger.go
  internal/apmschema/jsonschema/metricsets/metricset.json
  internal/apmschema/jsonschema/span_subtype.json
  internal/apmschema/jsonschema/span_type.json
  internal/apmschema/jsonschema/spans/span.json
  internal/apmschema/jsonschema/transaction_name.json
  internal/apmschema/jsonschema/transaction_type.json
  internal/apmschema/jsonschema/transactions/transaction.json
  internal/apmschema/update.sh
  logger.go
  metrics.go
  model/marshal.go
  model/marshal_fastjson.go
  model/model.go
  modelwriter.go
  span.go
  tracer.go
  transaction.go
  transaction_test.go
  utils.go
Labels: [zube]: Inbox

#592 Optimise BodyCapturer
  CHANGELOG.md
  capturebody.go
  capturebody_test.go
  module/apmecho/middleware.go
  module/apmechov4/middleware.go
  module/apmgin/middleware.go
  module/apmhttp/handler.go
  module/apmhttp/handler_test.go
  module/apmhttprouter/handler.go
  module/apmrestful/filter.go
Labels: [zube]: In Review

#596 ci: docs stage is handled within the elasticsearch-ci/docs
  Jenkinsfile
Labels: [zube]: In Review, automation, ci

#599 docs: add ELASTIC_APM_DISABLE_METRICS docs
  docs/configuration.asciidoc
  docs/metrics.asciidoc
Labels: [zube]: In Review

#600 Introduce `ELASTIC_APM_BREAKDOWN_METRICS` config
  breakdown.go
  breakdown_test.go
  docs/configuration.asciidoc
  env.go
  tracer.go
  transaction.go
Labels: [zube]: In Review

#598 docs: add mentions of central config
  docs/configuration.asciidoc
Labels: [zube]: In Review
