Repository elastic/apm-agent-go, pull requests merged in 2019-08, with the labels that each got.

#606 ci: use windows-2019-immutable workers
  Jenkinsfile
Labels: automation, ci

#614 ci(jenkins): avoid using the any agent to skip running in the master-worker
  Jenkinsfile
Labels: automation, ci, enhancement

#615 ci(jenkins): this is required to avoid using a common worker
  Jenkinsfile
Labels: automation, bug, ci

#619 ci(jenkins): revert none agent
  Jenkinsfile
Labels: automation, ci
