Repository elastic/apm-agent-go, pull requests merged in 2019-04, with the labels that each got.

#492 module/apmot: remove workaround for ended tx
  module/apmot/context.go
  module/apmot/doc.go
  module/apmot/span.go
  module/apmot/tracer.go
  module/apmot/tracer_test.go
Labels: [zube]: In Review

#495 Add apmchi module to support github.com/go-chi/chi
  module/apmchi/go.mod
  module/apmchi/go.sum
  module/apmchi/middleware.go
  module/apmchi/middleware_test.go
  scripts/Dockerfile-testing
Labels: [zube]: In Review

#499 Add changelog and basic docs for apmchi
  CHANGELOG.md
  docs/instrumenting.asciidoc
  docs/supported-tech.asciidoc
  module/apmchi/doc.go
Labels: [zube]: In Review

#500 Add examples for Transaction.Context.SetUser*
  context.go
  example_context_test.go
Labels: [zube]: In Review

#501 [APM-CI] update codecov step
  Jenkinsfile
Labels: automation

#511 docs: add tag information
  docs/api.asciidoc
Labels: docs
