Repository elastic/apm-agent-go, pull requests merged in 2019-06, with the labels that each got.

#547 module/{apmgopg,apmgoredis}: require Go 1.11
  .appveyor.yml
  .travis.yml
  Jenkinsfile
  module/apmgopg/doc.go
  module/apmgopg/hook.go
  module/apmgopg/hook_test.go
  module/apmgoredis/client.go
  module/apmgoredis/client_test.go
  module/apmgoredis/doc.go
  module/apmgoredis/integration_test.go
Labels: [zube]: In Review

#554 remove httprouter import from New example
  docs/instrumenting.asciidoc
Labels: [zube]: In Review

#552 feat(jenkins): new notifications and reports to Elasticsearch
  Jenkinsfile
Labels: [zube]: In Review, automation

#562 module/apmprometheus: remove refs to DefObjectives
  module/apmprometheus/gatherer_test.go
Labels: [zube]: In Review

#559 Introduce ELASTIC_APM_STACK_TRACE_LIMIT
  CHANGELOG.md
  docs/configuration.asciidoc
  env.go
  env_test.go
  error.go
  error_test.go
  internal/pkgerrorsutil/pkgerrors.go
  module/apmzerolog/stack.go
  span.go
  stacktrace/stacktrace.go
  stacktrace/stacktrace_test.go
  tracer.go
  tracer_test.go
  transaction.go
Labels: [zube]: In Review

#561 Truncate error.culprit
  CHANGELOG.md
  internal/apmschema/jsonschema/context.json
  internal/apmschema/jsonschema/errors/error.json
  internal/apmschema/jsonschema/metadata.json
  internal/apmschema/jsonschema/request.json
  internal/apmschema/jsonschema/service.json
  internal/apmschema/jsonschema/spans/span.json
  internal/apmschema/jsonschema/stacktrace_frame.json
  internal/apmschema/jsonschema/system.json
  internal/apmschema/jsonschema/user.json
  modelwriter.go
  validation_test.go
Labels: [zube]: In Review

#563 feat(jenkins): GH Checks for the PR
  Jenkinsfile
Labels: automation, ci

#558 [docs][7.2] update environment config
  docs/configuration.asciidoc
Labels: docs

#565 ci(jenkins): trigger async ITs and update github check for the pull request
  Jenkinsfile
Labels: automation, ci

#571 ci(jenkins): notify first time contributor github check
  Jenkinsfile
Labels: automation, ci

#570 ci: notify on cleanup stage
  Jenkinsfile
Labels: [zube]: In Review, automation
