Repository elastic/apm-agent-go, pull requests merged in 2020-01, with the labels that each got.

#695 ci(jenkins): appveyor and travis are decommissioned
  .appveyor.yml
  .travis.yml
Labels: automation, ci

#696 Add reference repo for apm-agent-go
  .ci/jobs/defaults.yml
  Jenkinsfile
Labels: automation, ci

#702 ci(jenkins): Install latest golang version for Windows
  Jenkinsfile
  scripts/jenkins/windows/install-tools.bat
  scripts/jenkins/windows/uninstall-tools.bat
Labels: automation

#703 Revert "ci(jenkins): Install latest golang version for Windows (#702)"
  Jenkinsfile
  scripts/jenkins/windows/install-tools.bat
Labels: automation

#705 ci(jenkins): fixes known issue with params/env variables
  Jenkinsfile
Labels: automation, bug, ci
