Repository elastic/apm-agent-go, pull requests merged in 2020-02, with the labels that each got.

#714 ci(jenkins): transform jUnit output for test stages
  .gitignore
  scripts/jenkins/build-test.sh
Labels: automation, ci

#719 [docs] Add EOL table
  CONTRIBUTING.md
  docs/index.asciidoc
  docs/upgrading.asciidoc
Labels: docs

#722 fixing wrong documents
  docs/instrumenting.asciidoc
  docs/introduction.asciidoc
Labels: docs

#720 ci(jenkins): run opbeans validation per PR
  Jenkinsfile
Labels: automation, ci

#724 ci(jenkins): retry/sleep to avoid timeout issues with GitHub
  Jenkinsfile
Labels: automation, ci

#726 ci(jenkins): apm-its-downstream params has changed
  Jenkinsfile
Labels: automation
