Repository elastic/apm-agent-go, pull requests merged in 2021-04, with the labels that each got.

#926 Add apmchiv5 module to support github.com/go-chi/chi/v5
  module/apmchiv5/doc.go
  module/apmchiv5/go.mod
  module/apmchiv5/go.sum
  module/apmchiv5/middleware.go
  module/apmchiv5/middleware_test.go
  scripts/Dockerfile-testing
Labels: agent-go

#927 add s3 session wrapper
  Makefile
  docs/instrumenting.asciidoc
  docs/supported-tech.asciidoc
  model/generate.sh
  model/marshal_fastjson.go
  model/model.go
  module/apmawssdkgo/doc.go
  module/apmawssdkgo/go.mod
  module/apmawssdkgo/go.sum
  module/apmawssdkgo/session.go
  module/apmawssdkgo/session_test.go
  scripts/Dockerfile-testing
  spancontext.go
Labels: agent-go

#930 scripts: pin go-restful to v3.4.0
  scripts/before_install.sh
Labels: agent-go

#928 Instrument DynamoDB calls
  CHANGELOG.asciidoc
  docs/instrumenting.asciidoc
  docs/supported-tech.asciidoc
  module/apmawssdkgo/dynamodb.go
  module/apmawssdkgo/s3.go
  module/apmawssdkgo/session.go
  module/apmawssdkgo/session_test.go
Labels: agent-go

#932 synchronize schema spec
  internal/apmschema/jsonschema/error.json
  internal/apmschema/jsonschema/metadata.json
  internal/apmschema/jsonschema/transaction.json
Labels: agent-go, automation

#933 Instrument RPC calls to amazon SQS
  CHANGELOG.asciidoc
  docs/instrumenting.asciidoc
  docs/supported-tech.asciidoc
  module/apmawssdkgo/session.go
  module/apmawssdkgo/sqs.go
  module/apmawssdkgo/sqs_test.go
Labels: agent-go

#904 module/apmgrpc: record underlying HTTP/2 context
  CHANGELOG.asciidoc
  module/apmgrpc/client.go
  module/apmgrpc/client_test.go
  module/apmgrpc/server.go
  module/apmgrpc/server_test.go
Labels: agent-go

#937 test: synchronizing json spec
  CHANGELOG.asciidoc
  internal/sqlscanner/scanner.go
  internal/sqlscanner/scanner_test.go
  internal/testdata/json-specs/sql_signature_examples.json
  internal/testdata/json-specs/sql_token_examples.json
  internal/testdata/json-specs/wildcard_matcher_tests.json
  internal/wildcard/matcher_test.go
  module/apmsql/signature_test.go
Labels: agent-go, automation

#938 Add support for instrumenting AWS SNS
  CHANGELOG.asciidoc
  docs/instrumenting.asciidoc
  docs/supported-tech.asciidoc
  module/apmawssdkgo/session.go
  module/apmawssdkgo/sns.go
  module/apmawssdkgo/sns_test.go
  module/apmawssdkgo/sqs.go
  module/apmawssdkgo/sqs_test.go
Labels: agent-go

#906 Capture request body in CaptureError calls
  CHANGELOG.asciidoc
  apmtest/httpsuite.go
  capturebody.go
  context.go
  gocontext.go
  internal/apmcontext/context.go
  module/apmecho/middleware.go
  module/apmecho/middleware_test.go
  module/apmechov4/middleware.go
  module/apmechov4/middleware_test.go
  module/apmgin/middleware.go
  module/apmgin/middleware_test.go
  module/apmhttp/handler.go
  module/apmhttp/handler_test.go
  module/apmhttprouter/handler.go
  module/apmhttprouter/router_test.go
  module/apmnegroni/middleware_test.go
  module/apmrestful/filter.go
  module/apmrestful/filter_test.go
Labels: agent-go

#949 Add context message queue name
  model/marshal_fastjson.go
  model/model.go
  module/apmawssdkgo/sns.go
  module/apmawssdkgo/sns_test.go
  module/apmawssdkgo/sqs.go
  module/apmawssdkgo/sqs_test.go
  spancontext.go
Labels: agent-go

#953 BodyCapturer: Fix NPE on benchmark when nil Context.request
  capturebody.go
Labels: agent-go, bug

#954 apmot: Handle `http.host` tag as `url.Host`
  CHANGELOG.asciidoc
  module/apmot/span.go
  module/apmot/tracer_test.go
Labels: agent-go, enhancement

#956 apm: add ParentID methods to Span and Transaction
  CHANGELOG.asciidoc
  docs/api.asciidoc
  modelwriter.go
  span.go
  span_test.go
  transaction.go
  transaction_test.go
Labels: agent-go, enhancement

#951 documentation updates
  docs/api.asciidoc
  docs/configuration.asciidoc
  docs/context-propagation.asciidoc
  docs/custom-instrumentation.asciidoc
  docs/instrumenting.asciidoc
  docs/introduction.asciidoc
  docs/log-correlation.asciidoc
  docs/metrics.asciidoc
  docs/opentracing.asciidoc
  docs/troubleshooting.asciidoc
Labels: agent-go, docs
