Repository elastic/apm-agent-go, pull requests merged in 2021-09, with the labels that each got.

#1120 Pin some more dependencies for pre-modules Go
  scripts/before_install.sh
Labels: agent-go

#1118 synchronize schema spec
  internal/apmschema/jsonschema/error.json
  internal/apmschema/jsonschema/transaction.json
Labels: automation, agent-go

#1117 test: synchronizing json spec
  internal/testdata/json-specs/span_types.json
Labels: automation, agent-go

#999 add APM instrumentation middleware module for Fiber framework
  docs/instrumenting.asciidoc
  docs/supported-tech.asciidoc
  module/apmfiber/doc.go
  module/apmfiber/go.mod
  module/apmfiber/go.sum
  module/apmfiber/middleware.go
  module/apmfiber/middleware_test.go
  scripts/Dockerfile-testing
Labels: [zube]: In Review, agent-go

#1121 synchronize schema spec
  internal/apmschema/jsonschema/error.json
  internal/apmschema/jsonschema/metadata.json
  internal/apmschema/jsonschema/span.json
  internal/apmschema/jsonschema/transaction.json
Labels: automation, agent-go

#1124 synchronize schema spec
  internal/apmschema/jsonschema/error.json
  internal/apmschema/jsonschema/span.json
  internal/apmschema/jsonschema/transaction.json
Labels: automation, agent-go

#1126 release: Update `CONTRIBUTING` with more context
  CONTRIBUTING.md
Labels: agent-go

#1125 release: Bump versions to `1.14.0`
  CHANGELOG.asciidoc
  docs/upgrading.asciidoc
  internal/apmgodog/go.mod
  internal/apmversion/version.go
  internal/tracecontexttest/go.mod
  module/apmawssdkgo/go.mod
  module/apmazure/go.mod
  module/apmbeego/go.mod
  module/apmchi/go.mod
  module/apmchiv5/go.mod
  module/apmecho/go.mod
  module/apmechov4/go.mod
  module/apmelasticsearch/go.mod
  module/apmelasticsearch/internal/integration/go.mod
  module/apmfasthttp/go.mod
  module/apmfiber/go.mod
  module/apmgin/go.mod
  module/apmgocql/go.mod
  module/apmgokit/go.mod
  module/apmgometrics/go.mod
  module/apmgopg/go.mod
  module/apmgopgv10/go.mod
  module/apmgoredis/go.mod
  module/apmgoredisv8/go.mod
  module/apmgorilla/go.mod
  module/apmgorm/go.mod
  module/apmgormv2/go.mod
  module/apmgrpc/go.mod
  module/apmhttp/go.mod
  module/apmhttprouter/go.mod
  module/apmlambda/go.mod
  module/apmlogrus/go.mod
  module/apmmongo/go.mod
  module/apmnegroni/go.mod
  module/apmot/go.mod
  module/apmprometheus/go.mod
  module/apmredigo/go.mod
  module/apmrestful/go.mod
  module/apmrestfulv3/go.mod
  module/apmsql/go.mod
  module/apmzap/go.mod
  module/apmzerolog/go.mod
  scripts/genmod/go.mod
  version.go
Labels: agent-go

#1127 [CI] use obltGitHubComments
  Jenkinsfile
Labels: automation, agent-go

#1128 scripts: Fixup `tagversion.sh` for Darwin
  scripts/tagversion.sh
Labels: agent-go

#1130 synchronize schema spec
  internal/apmschema/jsonschema/transaction.json
Labels: automation, agent-go

#1129 Stop recording `http.request.socket.encrypted`
  CHANGELOG.asciidoc
  context.go
  gofuzz.go
  model/marshal_fastjson.go
  model/marshal_test.go
  model/model.go
  module/apmfiber/middleware_test.go
  module/apmgrpc/server_test.go
  module/apmhttp/handler_http2_test.go
Labels: [zube]: In Review, v7.16.0
