Repository elastic/apm-agent-go, pull requests merged in 2021-11, with the labels that each got.

#1145 add histogram
  CHANGELOG.asciidoc
  metrics.go
  model/marshal.go
  model/marshal_fastjson.go
  model/marshal_test.go
  model/model.go
  module/apmprometheus/gatherer.go
  module/apmprometheus/gatherer_test.go
Labels: agent-go

#1151 feat(apmgrpc): wrap the server-stream with transaction-ctx
  module/apmgrpc/go.sum
  module/apmgrpc/server.go
  module/apmgrpc/server_test.go
Labels: agent-go

#1150 synchronize schema spec
  internal/apmschema/jsonschema/error.json
  internal/apmschema/jsonschema/metricset.json
Labels: automation, agent-go

#1158 Fix apmcloudutil logger assignment
  CHANGELOG.asciidoc
  utils.go
Labels: bug, agent-go

#1159 Fix data race in HTTP request header sanitisation
  CHANGELOG.asciidoc
  sanitizer.go
Labels: bug, agent-go

#1157 Update godog test integration
  internal/apmgodog/feature_test.go
  internal/apmgodog/formatter_test.go
  internal/apmgodog/go.mod
  internal/apmgodog/go.sum
  internal/apmgodog/suitecontext_test.go
  internal/apmgodog/testmain_test.go
  scripts/before_install.sh
Labels: agent-go

#1160 Set default outcome according to spec
  CHANGELOG.asciidoc
  error.go
  internal/apmgodog/suitecontext_test.go
  span.go
  span_test.go
  transaction.go
  transaction_test.go
Labels: agent-go
