Repository elastic/apm-agent-go, pull requests merged in 2021-12, with the labels that each got.

#1163 test: synchronizing json spec
  internal/testdata/json-specs/span_types.json
Labels: automation, agent-go

#1164 Increase test pipeline timeout
  Jenkinsfile
Labels: agent-go

#1165 release: Prepare `v1.15.0` version
  CHANGELOG.asciidoc
  docs/upgrading.asciidoc
  internal/apmgodog/go.mod
  internal/apmversion/version.go
  internal/tracecontexttest/go.mod
  module/apmawssdkgo/go.mod
  module/apmazure/go.mod
  module/apmbeego/go.mod
  module/apmchi/go.mod
  module/apmchiv5/go.mod
  module/apmecho/go.mod
  module/apmechov4/go.mod
  module/apmelasticsearch/go.mod
  module/apmelasticsearch/internal/integration/go.mod
  module/apmfasthttp/go.mod
  module/apmfiber/go.mod
  module/apmgin/go.mod
  module/apmgocql/go.mod
  module/apmgokit/go.mod
  module/apmgometrics/go.mod
  module/apmgopg/go.mod
  module/apmgopgv10/go.mod
  module/apmgoredis/go.mod
  module/apmgoredisv8/go.mod
  module/apmgorilla/go.mod
  module/apmgorm/go.mod
  module/apmgormv2/go.mod
  module/apmgrpc/go.mod
  module/apmhttp/go.mod
  module/apmhttprouter/go.mod
  module/apmlambda/go.mod
  module/apmlogrus/go.mod
  module/apmmongo/go.mod
  module/apmnegroni/go.mod
  module/apmot/go.mod
  module/apmprometheus/go.mod
  module/apmredigo/go.mod
  module/apmrestful/go.mod
  module/apmrestfulv3/go.mod
  module/apmsql/go.mod
  module/apmzap/go.mod
  module/apmzerolog/go.mod
  scripts/genmod/go.mod
  version.go
Labels: agent-go

#1169 Get rid of references from modules to apm/internal
  error.go
  gocontext.go
  internal/apmcontext/context.go
  module/apmchi/middleware.go
  module/apmchiv5/middleware.go
  module/apmecho/middleware_test.go
  module/apmechov4/middleware.go
  module/apmechov4/middleware_test.go
  module/apmfasthttp/context.go
  module/apmgocql/signature.go
  module/apmhttp/ignorer.go
  module/apmhttp/ignorer_test.go
  module/apmot/tracer_test.go
  module/apmot/wrapper.go
  module/apmsql/driver.go
  module/apmsql/signature.go
  module/apmzerolog/stack.go
  sqlutil/doc.go
  sqlutil/drivername.go
  sqlutil/scanner.go
  sqlutil/scanner_test.go
  sqlutil/token.go
  stacktrace/errors.go
Labels: breaking change, agent-go

#1174 ci: update opbeans branch to main
  Jenkinsfile
Labels: agent-go

#1178 deps: Pin `olivere/elastic` dependency
  scripts/before_install.sh
Labels: agent-go

#1176 jjbb: exclude update-specs branches
  .ci/jobs/defaults.yml
Labels: automation, agent-go, Team:Automation

#1175 Update ITs main
  Jenkinsfile
Labels: agent-go

#1177 error: Record `transaction.name` when available
  error.go
  error_test.go
  model/marshal_fastjson.go
  model/model.go
  modelwriter.go
Labels: enhancement, agent-go

#1179 synchronize schema spec
  internal/apmschema/jsonschema/transaction.json
Labels: automation, agent-go

#1180 fix: panic on gocql
  module/apmgocql/apmgocql_test.go
  module/apmgocql/observer.go
Labels: agent-go
