Repository elastic/apm-agent-go, pull requests merged in 2021-08, with the labels that each got.

#996 synchronize schema spec
  internal/apmschema/jsonschema/metadata.json
Labels: agent-go, automation

#997 Concurrency fixes
  CHANGELOG.asciidoc
  module/apmhttp/clienttrace.go
  span.go
Labels: agent-go

#998 Bump version to 1.13.1
  CHANGELOG.asciidoc
  internal/apmgodog/go.mod
  internal/apmversion/version.go
  internal/tracecontexttest/go.mod
  module/apmawssdkgo/go.mod
  module/apmbeego/go.mod
  module/apmchi/go.mod
  module/apmchiv5/go.mod
  module/apmecho/go.mod
  module/apmechov4/go.mod
  module/apmelasticsearch/go.mod
  module/apmelasticsearch/internal/integration/go.mod
  module/apmfasthttp/go.mod
  module/apmgin/go.mod
  module/apmgocql/go.mod
  module/apmgokit/go.mod
  module/apmgometrics/go.mod
  module/apmgopg/go.mod
  module/apmgopgv10/go.mod
  module/apmgoredis/go.mod
  module/apmgoredisv8/go.mod
  module/apmgorilla/go.mod
  module/apmgorm/go.mod
  module/apmgormv2/go.mod
  module/apmgrpc/go.mod
  module/apmhttp/go.mod
  module/apmhttprouter/go.mod
  module/apmlambda/go.mod
  module/apmlogrus/go.mod
  module/apmmongo/go.mod
  module/apmnegroni/go.mod
  module/apmot/go.mod
  module/apmprometheus/go.mod
  module/apmredigo/go.mod
  module/apmrestful/go.mod
  module/apmrestfulv3/go.mod
  module/apmsql/go.mod
  module/apmzap/go.mod
  module/apmzerolog/go.mod
  scripts/genmod/go.mod
  version.go
Labels: agent-go

#1002 send traceparent header to ES
  module/apmelasticsearch/client.go
  module/apmelasticsearch/client_test.go
  module/apmhttp/client.go
Labels: agent-go, v7.15.0

#1006 [apmawssdkgo] don't panic on unsupported services
  module/apmawssdkgo/session.go
  module/apmawssdkgo/session_test.go
Labels: agent-go

#1003 Infer destination service resource adapt public api
  model/model.go
  span.go
  span_test.go
  spancontext.go
  spancontext_test.go
Labels: [zube]: In Review, agent-go, v7.15.0

#1103 test: synchronizing json spec
  internal/testdata/json-specs/service_resource_inference.json
Labels: automation, agent-go

#1104 [apmfasthttp] set correct http status
  module/apmfasthttp/closer.go
  module/apmfasthttp/consts.go
  module/apmfasthttp/context.go
  module/apmfasthttp/go.mod
  module/apmfasthttp/recovery.go
  module/apmfasthttp/server.go
  module/apmfasthttp/server_test.go
Labels: agent-go

#1105 [apmazure] add blob storage
  docs/instrumenting.asciidoc
  docs/supported-tech.asciidoc
  module/apmazure/blob.go
  module/apmazure/blob_test.go
  module/apmazure/doc.go
  module/apmazure/go.mod
  module/apmazure/go.sum
  module/apmazure/storage.go
  scripts/Dockerfile-testing
  spancontext.go
Labels: agent-go

#1107 [apmazure] storage queue
  docs/instrumenting.asciidoc
  docs/supported-tech.asciidoc
  module/apmazure/blob.go
  module/apmazure/blob_test.go
  module/apmazure/go.mod
  module/apmazure/go.sum
  module/apmazure/queue.go
  module/apmazure/queue_test.go
  module/apmazure/storage.go
Labels: agent-go

#1109 [apmazure] file storage
  docs/instrumenting.asciidoc
  docs/supported-tech.asciidoc
  module/apmazure/file.go
  module/apmazure/file_test.go
  module/apmazure/go.mod
  module/apmazure/go.sum
  module/apmazure/storage.go
Labels: agent-go

#1110 re-flush until transaction has been closed
  module/apmfasthttp/server_test.go
Labels: agent-go

#1115 synchronize schema spec
  internal/apmschema/jsonschema/error.json
  internal/apmschema/jsonschema/span.json
  internal/apmschema/jsonschema/transaction.json
Labels: automation, agent-go
