Repository elastic/apm-agent-go, pull requests merged in 2022-01, with the labels that each got.

#1167 transaction: Stop recording breakdown metrics
  breakdown.go
  breakdown_internal_test.go
  breakdown_test.go
  transaction.go
Labels: enhancement, agent-go, v8.0.0

#1186 CI: use apm-integration-testing/7.x for v1
  Jenkinsfile
  scripts/before_install.sh
  tracecontext.go
  tracecontext_test.go
Labels: agent-go

#1185 remove unnecessary fasthttp import from apmfiber module
  module/apmfiber/middleware.go
Labels: agent-go

#1168 transport: Introduce NewHTTPTransportOptions
  transport/http.go
  transport/http_test.go
Labels: enhancement, agent-go, v8.0.0

#1188 handle special cases for span frames min duration
  span.go
  span_test.go
Labels: breaking change, agent-go

#1187 remove stacktrace.ContextSetter
  modelwriter.go
  stacktrace/context.go
  stacktrace/context_test.go
  tracer.go
  tracer_stats.go
Labels: breaking change, agent-go

#1195 Remove transport.Default
  CHANGELOG.asciidoc
  config.go
  example_test.go
  internal/apmgodog/suitecontext_test.go
  tracer.go
  tracer_test.go
  transport/default.go
  transport/default_test.go
  transport/discard.go
Labels: agent-go

#1172 module/apmechov4: bump echo version
  module/apmechov4/go.mod
  module/apmechov4/go.sum
Labels: agent-go

#1196 Include service name and version in User-Agent
  CHANGELOG.asciidoc
  config.go
  config_test.go
  env_test.go
  features/api_key.feature
  features/azure_app_service_metadata.feature
  features/outcome.feature
  features/user_agent.feature
  internal/apmgodog/suitecontext_test.go
  module/apmgin/bench_test.go
  module/apmhttp/handler_bench_test.go
  module/apmsql/apmsql_bench_test.go
  tracer_test.go
  transport/http.go
  transport/http_test.go
Labels: agent-go

#1199 Doc links update
  docs/api.asciidoc
  docs/configuration.asciidoc
  docs/introduction.asciidoc
  docs/upgrading.asciidoc
Labels: docs, agent-go

#1200 [1.x] Fix doc links
  docs/api.asciidoc
  docs/configuration.asciidoc
  docs/introduction.asciidoc
  docs/upgrading.asciidoc
Labels: agent-go, Team:Docs
