Repository elastic/apm-agent-go, pull requests merged in 2022-08, with the labels that each got.

#1260 synchronize schema spec
  internal/apmschema/jsonschema/metricset.json
Labels: automation, agent-go

#1279 feat: add service target fields support to sql module
  module/apmsql/conn.go
  module/apmsql/mysql/mysql_test.go
  module/apmsql/pgxv4/pq_test.go
  module/apmsql/pq/pq_test.go
Labels: agent-go

#1278 feat: add service target fields support to aws module
  module/apmawssdkgo/dynamodb.go
  module/apmawssdkgo/s3.go
  module/apmawssdkgo/session.go
  module/apmawssdkgo/session_test.go
  module/apmawssdkgo/sns.go
  module/apmawssdkgo/sns_test.go
  module/apmawssdkgo/sqs.go
  module/apmawssdkgo/sqs_test.go
Labels: agent-go

#1280 feat: add service target fields support to azure module
  module/apmazure/blob.go
  module/apmazure/file.go
  module/apmazure/queue.go
  module/apmazure/queue_test.go
  module/apmazure/storage.go
Labels: agent-go

#1282 fix: use the correct destination resource and name for azure queue
  module/apmazure/queue.go
  module/apmazure/queue_test.go
  module/apmazure/storage.go
Labels: agent-go

#1281 feat: add service target fields support to elasticsearch module
  module/apmelasticsearch/client.go
  module/apmelasticsearch/client_test.go
  module/apmelasticsearch/internal/integration/elastic_integration_test.go
  module/apmelasticsearch/internal/integration/olivere_integration_test.go
Labels: agent-go

#1284 fix: reformat code with go 1.19 to fix ci failure
  breakdown_test.go
  error.go
  fmt.go
  module/apmgorm/open.go
  module/apmhttp/traceheaders.go
  module/apmot/doc.go
  module/apmzerolog/stack.go
  span_compressed.go
  tracecontext.go
Labels: agent-go

#1289 docs: document ELASTIC_APM_SERVER_CA_CERT_FILE
  docs/configuration.asciidoc
Labels: agent-go

#1283 test: add testcase for sqs delete_batch operation
  module/apmawssdkgo/sqs_test.go
Labels: agent-go

#1288 fix: expand k8s pod discovery regex
  internal/apmhostutil/container_linux.go
  internal/apmhostutil/container_linux_test.go
Labels: agent-go

#1286 feat: update sns span.name to reflect the current spec
  module/apmawssdkgo/sns.go
  module/apmawssdkgo/sns_test.go
Labels: agent-go

#1290 tracer: Parse global labels per tracer
  CHANGELOG.asciidoc
  config.go
  tracer.go
Labels: enhancement, agent-go

#1293 test: verify Ubuntu cgroup line parsing for container ID
  internal/apmhostutil/container_linux_test.go
Labels: agent-go

#1285 feat: rename span_frames_min_duration to span_stack_trace_min_duration
  CHANGELOG.asciidoc
  config.go
  config_test.go
  docs/configuration.asciidoc
  env_test.go
  span.go
  span_test.go
  tracer.go
  tracer_test.go
  transaction.go
Labels: agent-go

#1297 fix: readd deprecated span_frames_min_duration option as fallback for older configuration
  config.go
  docs/configuration.asciidoc
  env_test.go
Labels: agent-go

#1299 docs: update correct env flag for loglevel
  docs/troubleshooting.asciidoc
Labels: agent-go
