Repository elastic/apm-agent-go, pull requests merged in 2022-02, with the labels that each got.

#1192 enable -race for tests
  Makefile
  config.go
  config_test.go
  internal/apmgodog/suitecontext_test.go
  internal/apmlog/logger.go
  internal/apmlog/logger_test.go
  module/apmgrpc/client.go
  tracer.go
  tracer_test.go
  utils.go
Labels: agent-go

#1204 test: synchronizing json spec
  internal/testdata/json-specs/span_types.json
Labels: automation, agent-go

#1206 Replace Sampler with ExtendedSampler
  CHANGELOG.asciidoc
  config.go
  sampler.go
  sampler_test.go
  tracer.go
  transaction.go
  transaction_test.go
Labels: breaking change, agent-go

#1205 Fold WarningLogger info Logger
  CHANGELOG.asciidoc
  apmtest/testlogger.go
  config.go
  logger.go
  tracer.go
Labels: breaking change, agent-go

#1207 test: synchronizing json spec
  internal/testdata/json-specs/w3c_distributed_tracing.json
Labels: automation, agent-go

#1208 tracer: Drop unsampled txs when APM Server >= 8.0
  CHANGELOG.asciidoc
  config_test.go
  tracer.go
  tracer_test.go
  transport/http.go
  transport/http_test.go
Labels: enhancement, breaking change, agent-go, v8.1.0

#1214 ci: go master version stage is not triggered
  Jenkinsfile
Labels: automation, agent-go

#1193 [apmfasthttp] fix: set response context with closer close
  module/apmfasthttp/closer.go
  module/apmfasthttp/context.go
  module/apmfasthttp/go.mod
  module/apmfasthttp/go.sum
  module/apmfasthttp/server.go
  module/apmfasthttp/server_test.go
  module/apmfiber/go.mod
  module/apmfiber/go.sum
  module/apmfiber/middleware_test.go
Labels: agent-go

#1216 Fix TestHTTPTransportWatchConfigContextCancelled
  transport/http_test.go
Labels: agent-go

#1217 Fix TestHTTPTransportWatchConfigContextCancelled
  transport/http_test.go
Labels: agent-go

#1218 Remove the deprecated SetTag methods in v2
  CHANGELOG.asciidoc
  context.go
  context_test.go
  docs/api.asciidoc
  spancontext.go
  spancontext_test.go
Labels: breaking change, agent-go

#1219 Unexport all of Tracer's fields
  CHANGELOG.asciidoc
  metrics_test.go
  tracer.go
  tracer_test.go
  transaction_test.go
  validation_test.go
Labels: breaking change, agent-go
