Repository elastic/apm-agent-go, pull requests merged in 2023-01, with the labels that each got.

#1371 restore instrumentation nav
  docs/instrumenting.asciidoc
Labels: docs, agent-go, test-plan-skip

#1372 [2.x] indent new apmpgx docs (#1371)
  docs/instrumenting.asciidoc
Labels: agent-go

#1364 feat: implement module for pgx/v5
  module/apmpgxv5/batch_tracer.go
  module/apmpgxv5/batch_tracer_test.go
  module/apmpgxv5/connect_tracer.go
  module/apmpgxv5/connect_tracer_test.go
  module/apmpgxv5/copy_tracer.go
  module/apmpgxv5/copy_tracer_test.go
  module/apmpgxv5/doc.go
  module/apmpgxv5/go.mod
  module/apmpgxv5/go.sum
  module/apmpgxv5/query_tracer.go
  module/apmpgxv5/query_tracer_test.go
  module/apmpgxv5/span.go
  module/apmpgxv5/tracer.go
  scripts/Dockerfile-testing
Labels: agent-go

#1366 synchronize schema spec
  internal/apmschema/jsonschema/span.json
  internal/apmschema/jsonschema/transaction.json
Labels: automation, agent-go

#1349 action: run matrix support
  .github/workflows/ci.yml
  .github/workflows/opentelemetry.yml
  .jenkins.yml
  Jenkinsfile
Labels: automation, agent-go, Team:Automation

#1376 action: use snapshoty
  .ci/snapshoty.yml
  .github/workflows/snapshoty.yml
  Jenkinsfile
Labels: automation, agent-go, Team:Automation

#1378 action: typo in the setup-go version
  .github/workflows/snapshoty.yml
Labels: automation, agent-go, Team:Automation
