Repository elastic/apm-agent-go, pull requests merged in 2025-03, with the labels that each got.

#1697 Drop support for go 1.22
  Makefile
  go.mod
  internal/apmgodog/go.mod
  internal/apmgodog/go.sum
  internal/apmschema/go.mod
  internal/tracecontexttest/go.mod
  module/apmawssdkgo/go.mod
  module/apmazure/go.mod
  module/apmbeego/go.mod
  module/apmchi/go.mod
  module/apmchiv5/go.mod
  module/apmecho/go.mod
  module/apmechov4/go.mod
  module/apmelasticsearch/go.mod
  module/apmelasticsearch/internal/integration/go.mod
  module/apmfasthttp/go.mod
  module/apmfiber/go.mod
  module/apmgin/go.mod
  module/apmgocql/go.mod
  module/apmgokit/go.mod
  module/apmgometrics/go.mod
  module/apmgopg/go.mod
  module/apmgopgv10/go.mod
  module/apmgoredis/go.mod
  module/apmgoredisv8/go.mod
  module/apmgorilla/go.mod
  module/apmgorm/go.mod
  module/apmgormv2/go.mod
  module/apmgrpc/go.mod
  module/apmhttp/go.mod
  module/apmhttprouter/go.mod
  module/apmlambda/go.mod
  module/apmlogrus/go.mod
  module/apmmongo/go.mod
  module/apmnegroni/go.mod
  module/apmot/go.mod
  module/apmotel/go.mod
  module/apmpgx/go.mod
  module/apmpgxv5/go.mod
  module/apmprometheus/go.mod
  module/apmredigo/go.mod
  module/apmrestful/go.mod
  module/apmrestfulv3/go.mod
  module/apmslog/go.mod
  module/apmsql/go.mod
  module/apmzap/go.mod
  module/apmzerolog/go.mod
  scripts/genmod/go.mod
  tools/go.mod
  tools/go.sum
Labels: agent-go

#1698 Release 2.7.0
  CHANGELOG.asciidoc
  internal/apmgodog/go.mod
  internal/apmschema/go.mod
  internal/apmversion/version.go
  internal/tracecontexttest/go.mod
  module/apmawssdkgo/go.mod
  module/apmazure/go.mod
  module/apmbeego/go.mod
  module/apmchi/go.mod
  module/apmchiv5/go.mod
  module/apmecho/go.mod
  module/apmechov4/go.mod
  module/apmelasticsearch/go.mod
  module/apmelasticsearch/internal/integration/go.mod
  module/apmfasthttp/go.mod
  module/apmfiber/go.mod
  module/apmgin/go.mod
  module/apmgocql/go.mod
  module/apmgokit/go.mod
  module/apmgometrics/go.mod
  module/apmgopg/go.mod
  module/apmgopgv10/go.mod
  module/apmgoredis/go.mod
  module/apmgoredisv8/go.mod
  module/apmgorilla/go.mod
  module/apmgorm/go.mod
  module/apmgormv2/go.mod
  module/apmgrpc/go.mod
  module/apmhttp/go.mod
  module/apmhttprouter/go.mod
  module/apmlambda/go.mod
  module/apmlogrus/go.mod
  module/apmmongo/go.mod
  module/apmnegroni/go.mod
  module/apmot/go.mod
  module/apmotel/go.mod
  module/apmpgx/go.mod
  module/apmpgxv5/go.mod
  module/apmprometheus/go.mod
  module/apmredigo/go.mod
  module/apmrestful/go.mod
  module/apmrestfulv3/go.mod
  module/apmslog/go.mod
  module/apmsql/go.mod
  module/apmzap/go.mod
  module/apmzerolog/go.mod
  scripts/genmod/go.mod
  version.go
Labels: agent-go

#1700 [docs] Remove AsciiDoc changelog file
  CHANGELOG.asciidoc
  CONTRIBUTING.md
  docs/reference/supported-technologies.md
  docs/release-notes/deprecations.md
  docs/release-notes/index.md
  docs/release-notes/toc.yml
Labels: docs, agent-go, Team:Docs

#1701 Remove fips mention from release notes
  docs/release-notes/index.md
Labels: agent-go

#1704 Updates navigation titles for release notes
  docs/release-notes/deprecations.md
  docs/release-notes/known-issues.md
Labels: agent-go, Team:Docs

#1705 [docs] Miscellaneous docs clean up
  docs/docset.yml
  docs/reference/configuration.md
  docs/reference/images/dynamic-config.svg
  docs/reference/metrics.md
Labels: docs, agent-go, Team:Docs

#1708 [docs] Remove reliance on temporary redirects
  docs/reference/log-correlation.md
Labels: agent-go
